server:
  port: 9000

spring:
  kafka:
    consumer:
      #cluster -> multiple broker registration check for connection failure
      bootstrap-servers: localhost:9093
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9093